name: List out the issues

on:
  workflow_dispatch

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List issues and add comments
        uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login;
            const { data: issues } = await github.rest.issues.listForRepoIssues({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator,
              state: 'open'
            });

            const tenMinutesAgo = new Date();
            tenMinutesAgo.setMinutes(tenMinutesAgo.getMinutes() - 10);

            for (const issue of issues) {
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                per_page: 100
              });

              const lastComment = comments[comments.length - 1];

              if (!lastComment || new Date(lastComment.created_at) < tenMinutesAgo) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: 'Issue is inactive'
                });
              }
            }
