name: List out and update issues

on:
  workflow_dispatch

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List and update issues
        uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login;
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'open'
            });
            const issues = await github.paginate(opts);

            for (let i = 0; i < issues.length; i++) {
              const issue = issues[i];
              const issueLastUpdated = new Date(issue.updated_at);
              const currentDate = new Date();

              // Calculate the time difference in milliseconds
              const timeDifference = currentDate - issueLastUpdated;
              const fourDaysInMilliseconds = 4 * 24 * 60 * 60 * 1000; // 4 days

              if (timeDifference >= fourDaysInMilliseconds && issue.state === 'open') {
                console.log('Issue ' + issue.number + ' needs an update');
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: 'Hey, this is a test comment.';
                });
              }
            }
