name: List out and update issues

on:
  workflow_dispatch

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List and update issues
        uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login;
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              creator,
              state: 'open'
            });
            const issues = await github.paginate(opts);

            for (const issue of issues) {
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                per_page: 100
              });

              if (comments.data.length > 0) {
                const lastComment = comments.data.pop();
                const lastCommentDate = new Date(lastComment.created_at);
                const currentDate = new Date();

                // Calculate the time difference in milliseconds
                const timeDifference = currentDate - lastCommentDate;
                const oneDayInMilliseconds = 24 * 60 * 60 * 1000; // 1 day

                if (timeDifference >= oneDayInMilliseconds) {
                  console.log(`Issue ${issue.number} needs an update`);
                  const commentText = "Please give some update.";
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    body: Hey this is test comment
                  });
                }
              }
            }
