
name: Create Release Build

on:
  release:
    types: [released, prereleased]

jobs:

  check-release:
    name: 1st file
    uses: krushna1512/reusable_workflow/.github/workflows/check-release.yml@main
    with:
     release: ${{ inputs.release }}
    secrets: inherit
    

  check-history:
    name: Check if release is behind
    needs: check-release
    uses: krushna1512/reusable_workflow/.github/workflows/check-history.yml@main
    secrets: inherit

  check-build:
      name: Check if build is behind
      needs: [ check-release, check-history ]
      if: ${{ needs.check-history-job.outputs.clean == 'true' && ( needs.check-release.outputs.prefix == 'release' || needs.check-release.outputs.prefix == 'prerelease' ) }}
      uses: krushna1512/reusable_workflow/.github/workflows/check-history.yml@main
      secrets: inherit

 
        
