
name: Create Release Build

on:
  release:
    types: [released, prereleased]

jobs:

  check-history:
    name: Check if release is behind
    uses: krushna1512/reusable_workflow/.github/workflows/check-history.yml@main
    secrets: inherit


