name: Deploy

on:
  workflow_dispatch:
    inputs:
      deployment-env:
        description: 'Deployment Environment'
        required: true
        default: 'stg'
        type: choice
        options:
          - stg
          - prod
      run-npm-i:
        description: 'Run npm i'
        required: true
        default: 'false'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set deployment environment
      id: set-env
      run: echo "DEPLOYMENT_ENV=${{ github.event.inputs['deployment-env'] }}" >> $GITHUB_ENV

    - name: Create deploy script
      run: |
        cat <<END >deploy.sh
        #!/bin/bash
        echo "Deployment environment: $DEPLOYMENT_ENV"
        if [ "${{ github.event.inputs['run-npm-i'] }}" == "true" ]; then
          echo "Checkbox is checked. Running run-npm-i command:"
          pwd
        else
          echo "Checkbox is not checked. Skipping run-npm-i command."
        fi
        END
      shell: bash

    - name: Make deploy script executable
      run: chmod +x deploy.sh

    - name: Run deploy script
      run: ./deploy.sh
