name: run NPM CI  or not

on:
  workflow_dispatch:
    inputs:
      deployment-env:
        description: 'Deployment Environment'
        required: true
        default: 'stg'
        type: choice
        options:
          - stg
          - prod
      run-pwd:
        description: 'Run pwd'
        required: true
        default: 'false'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set deployment environment
      id: set-env
      run: echo "DEPLOYMENT_ENV=${{ github.event.inputs['deployment-env'] }}" >> $GITHUB_ENV

    - name: Run pwd if checked
      if: ${{ github.event.inputs['run-pwd'] == 'true' }}
      run: pwd
