name: 'without'

on:
  workflow_dispatch:

jobs:
  check_inactive_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github

      - name: Add comment to inactive issues
        run: |
          const { GitHub, context } = require('@actions/github');

          async function addCommentToInactiveIssues() {
            const octokit = new GitHub(process.env.GITHUB_TOKEN);
            const issuesResponse = await octokit.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const issues = issuesResponse.data;
            const fourDaysAgo = new Date();
            fourDaysAgo.setDate(fourDaysAgo.getDate() - 4);

            for (const issue of issues) {
              const lastActivityDate = new Date(issue.updated_at);
              if (lastActivityDate < fourDaysAgo && issue.comments === 0) {
                const commentBody = {
                  issue_number: issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: "It seems there has been no activity on this issue for the past four days. If you still require assistance, please let us know."
                };

                await octokit.rest.issues.createComment(commentBody);
              }
            }
          }

          addCommentToInactiveIssues();
