name: Print Repo Name

on:
  workflow_dispatch:

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print full repository name
        run: echo "Full repository name is: ${{ github.repository }}"

      - name: Extract and print repository name
        run: |
          REPO_NAME=${{ github.repository }}
          REPO_NAME_ONLY=$(echo $REPO_NAME | cut -d'/' -f2)
          echo "Repository name is: $REPO_NAME_ONLY"
