name: Trigger

on:
  workflow_dispatch:
    inputs:
      mention:
        description: 'Mention owner/assignee'
        required: true
        type: choice
        default: 'owner'
        options: ['owner', 'assignees']
   
jobs:
  trigger-workflow:
    name: Trigger Reusable Workflow
    uses: krushna1512/reusable_workflow/.github/workflows/automate_comment.yaml@main
    with:
      days: 3
      comment: 'h'
      mention: ${{ github.event.inputs.mention }}
