name: Trigger

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days for considering an issue outdated'
        required: true
        type: string
        
      comment:
        description: 'Comment message'
        required: true
        type: string
      mention:
        description: 'Mention owner/assignee'
        required: true
        type: choice
        options: ['owner', 'assignees']
   
jobs:
  trigger-workflow:
    name: Trigger Reusable Workflow
    uses: krushna1512/reusable_workflow/.github/workflows/automate_comment1.yaml@main
    with:
      days: ${{ github.event.inputs.days }}
      comment: ${{ github.event.inputs.comment }}
      mention: ${{ github.event.inputs.mention }}
