name: Trigger Reusable Workflow 3

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:
    inputs:
      comment:
        description: 'Comment message'
        default: 'This issue has not been updated recently, could you please provide an update?'
      mention:
        description: 'Mention owner/assignee'
        default: 'owner'
        type: choice
        options: ['owner', 'assignees']

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow triggered by scheduler
        id: check-scheduler
        run: echo "::set-output name=is_scheduler_triggered::${{ contains(github.event_name, 'schedule') }}"
          
      - name: Trigger Reusable Workflow
        if: steps.check-scheduler.outputs.is_scheduler_triggered == 'true'
        uses: krushna1512/reusable_workflow/.github/workflows/automate_comment1.yaml@main
        with: 
          days: 4  # Default value of 4 days
          comment: 'hey'  # Default comment message
          mention: 'owner'  # Default mention owner
          
      - name: Trigger Reusable Workflow
        if: steps.check-scheduler.outputs.is_scheduler_triggered != 'true'
        uses: krushna1512/reusable_workflow/.github/workflows/automate_comment1.yaml@main
        with: 
          days: 4  # Default value of 4 days
          comment: 'hey'  # Default comment message
          mention: 'owner'  # Default mention owner
