name: Redmine final

on:
  workflow_dispatch:
    inputs:
      redmine_issue_id:
        description: "Redmine Issue ID"
        required: true
      deploy_environment:
        description: "Deployment Environment (e.g., staging, production)"
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    outputs:
      deployment_status: ${{ steps.set_status.outputs.status }}  

    steps:
    - name: Dummy Deployment Step
      id: deploy
      run: |
        echo "Starting deployment..."
        # Simulating a deployment step
        if [ "$RANDOM" -gt 20000 ]; then
          echo "Deployment failed!"
          exit 1
        else
          echo "Deployment succeeded!"
        fi

    - name: Set Deployment Status
      id: set_status
      continue-on-error: true
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "::set-output name=status::Deployment completed successfully."
        else
          echo "::set-output name=status::Deployment failed during execution."
        fi
      if: always() 

  redmine_notification:
    needs: deployment
    if: always()
    secrets: inherit
    uses: krushna1512/reusable_workflow/.github/workflows/redmine.yml@main
    with: 
      deployment_status: ${{ needs.deployment.outputs.deployment_status }}
    
    
