name: Deployment Workflow with Redmine Notification

on:
  workflow_dispatch:
    inputs:
      redmine_issue_id:
        description: "Redmine Issue ID"
        required: true
    
jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Dummy Deployment Step
      id: deploy
      run: |
        echo "Starting deployment..."
        # Simulating a deployment step
        if [ "$RANDOM" -gt 20000 ]; then
          echo "Deployment failed!"
          exit 1
        else
          echo "Deployment succeeded!"
        fi

    - name: Set Deployment Status
      id: deployment_status
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "status=Deployment completed successfully." >> $GITHUB_ENV
        else
          echo "status=Deployment failed during execution." >> $GITHUB_ENV
        fi

  redmine_notification:
    needs: deployment
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Send Redmine Comment
      env:
        REDMINE_ISSUE_ID: ${{ github.event.inputs.redmine_issue_id }}
        REDMINE_API_KEY: 1575c3fb0e3c75e8261b9903ebbba14362bcc09f
        DEPLOYMENT_STATUS: ${{ env.status }}
      run: |
        echo "Sending deployment status to Redmine..."
        curl -X PUT "https://redmine.yapsody.net/issues/${REDMINE_ISSUE_ID}.json" \
        -H "Content-Type: application/json" \
        -H "X-Redmine-API-Key: ${REDMINE_API_KEY}" \
        -d "{\"issue\": {\"notes\": \"Tesing from local workflow\"}}"
