name: Deploy Release

run-name: Deploy to ${{ inputs.deploy-environment }} environment Issue Id - ${{ inputs.issue-id }}

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Tag to Deploy'
        required: true
        type: text
      issue-id:
        description: 'Issue ID'
        required: true
        type: text
      deploy-environment:
        description: 'Deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - 'secondstaging'
          - 'staging'
          - 'production'
      

jobs:
  deploy:
    name: Deployment Job
    runs-on: ubuntu-latest
    steps:
      - name: Echo Statement
        run: echo "Deploying release ${{ inputs.release }} to ${{ inputs.deploy-environment }} environment"
