name: Trigger Reusable Workflow

on:
  workflow_dispatch  # Runs every day at midnight UTC

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Step to checkout the repository containing the reusable workflow

      - name: Dispatch Workflow
        id: dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: krushna1512/reusable_workflow
          event-type: automate-comment
          client-payload: |
            {
              "days": 4,
              "comment": "Hey",
              "mention": "owner"
            }
        # Step to dispatch the reusable workflow from the specified repository

      - name: Debug Dispatch Workflow
        run: |
          echo "Workflow Run ID: ${{ steps.dispatch.outputs.workflow-run-id }}"
          echo "Event Type: ${{ steps.dispatch.outputs.event-type }}"
          echo "Result: ${{ steps.dispatch.outputs.result }}"
        # Step to display the outputs of the Dispatch Workflow step for debugging
