name: Trigger Reusable Workflow

on:
  workflow_dispatch  # Runs every day at midnight UTC

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: actions/checkout@v2  # Checkout the repository containing the reusable workflow

      - name: Dispatch Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: krushna1512/reusable_workflow
          event-type: automate-comment
          client-payload: |
            {
              "days": 4,
              "comment": "Hey",
              "mention": "owner"
            }

