name: Trigger Reusable Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: krushna1512/reusable_workflow/.github/workflows/automate_comment.yaml@main
        with:
          days: 4
          comment: 'Hey'
          mention: 'owner'

