name: Trigger Reusable Workflow

on:
  workflow_dispatch

jobs:
  trigger-workflow:
    name: Trigger Reusable Workflow
    uses: krushna1512/reusable_workflow/.github/workflows/automate_comment1.yaml@main
    with:
      minutes: 1
      comment: 'h'
      mention: 'assignees' # Set 'mention' parameter to 'assignees' to override the default value
