name: Trigger Reusable Workflow

on:
  workflow_dispatch # Runs every day at midnight UTC

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Reusable Workflow
        uses: krushna1512/reusable_workflow@main
        with:
          days: 4
          comment: 'Hey'
          mention: 'owner'
