name: Trigger Reusable Workflow

on:
  workflow_dispatch

jobs:
  trigger-workflow:
    name: Trigger Reusable Workflow
    uses: krushna1512/reusable_workflow/.github/workflows/test1.yml@main
    with:
      day: 1
      comment: 'h'
      mention: 'assignee' # Set 'mention' parameter to 'assignees' to override the default value
