name: Trigger Reusable Workflow

on:
  schedule:
    - cron: '*/6 * * * *' 

jobs:
  trigger-workflow:
        name: Trigger Reusable Workflow
        uses: krushna1512/reusable_workflow/.github/workflows/automate_comment.yaml@main
        with:
          days: 1
          comment: 'Hey'
          mention: 'owner'
