name: Trigger Reusable Workflow

on:
  workflow_dispatch: # Runs every day at midnight UTC

jobs:
  call-workflow-passing-data:
    uses: krushna1512/reusable_workflow/.github/workflows/automate_comment.yaml@main
    with:
      days: 4
      comment: 'Hey'
      mention: 'owner'

