name: Automate Comment

on:
  schedule:
   - cron: '*/6 * * * *'

jobs:
  trigger-workflow:
    name: Trigger Reusable Workflow
    uses: krushna1512/reusable_workflow/.github/workflows/test1.yml@main
    with:
      day: 4
      comment: 'This issue is not updated since 4 days, can you please give us some update here?'
      owner_or_assignee: 'assignee' 
