name: 'Without'

on:
  workflow_dispatch:

jobs:
  commentOnInactiveIssues:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on inactive issues
        uses: actions/github-script@v6
        with:
          script: |
            const octokit = context.octokit;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const currentDateTimeMinusFourDays = new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString();
            
            const response = await octokit.request('GET /repos/{owner}/{repo}/issues', {
              owner: owner,
              repo: repo,
              state: 'open',
              per_page: 100
            });

            const issues = response.data;

            for (const issue of issues) {
              const commentsResponse = await octokit.request('GET /repos/{owner}/{repo}/issues/{issue_number}/comments', {
                owner: owner,
                repo: repo,
                issue_number: issue.number,
                per_page: 100
              });

              const comments = commentsResponse.data;

              const lastComment = comments[comments.length - 1];

              if (!lastComment || lastComment.created_at < currentDateTimeMinusFourDays) {
                const comment = `Hello @${owner}! It seems no activity has been recorded on this issue for the past 4 days. Is there anything I can assist you with?`;

                await octokit.request('POST /repos/{owner}/{repo}/issues/{issue_number}/comments', {
                  owner: owner,
                  repo: repo,
                  issue_number: issue.number,
                  body: comment
                });
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
