on: pull_request_target

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Check for inactive issues
        uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login;
            const fourDaysAgo = new Date();
            fourDaysAgo.setDate(fourDaysAgo.getDate() - 4);

            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              { ...context.repo, state: 'open' }
            );

            for (const issue of issues) {
              const lastActivityDate = new Date(issue.updated_at);
              if (lastActivityDate < fourDaysAgo && issue.comments === 0) {
                await github.rest.issues.createComment({
                  issue_number: issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `It seems there has been no activity on this issue for the past four days. If you still require assistance, please let us know.`
                });
              }
            }
