name: 'Without'

on:
  workflow_dispatch:

jobs:
  commentOnInactiveIssues:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub Script
        uses: actions/github-script@v6

      - name: Comment on inactive issues
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          const currentDateTime = new Date().toISOString();
          const currentDateTimeMinusFourDays = new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString();

          github.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          }).then(({ data: comments }) => {
            const lastComment = comments[comments.length - 1];

            if (!lastComment || lastComment.created_at < currentDateTimeMinusFourDays) {
              const comment = `Hello @${context.repo.owner}! It seems no activity has been recorded on this issue since ${currentDateTime}. Is there anything I can assist you with?`;

              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }
          });
