name: 'without'

on:
  workflow_dispatch:

jobs:
  check_inactive_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for inactive issues
        uses: octokit/request-action@v2.x
        id: issues
        with:
          route: GET /repos/:owner/:repo/issues?state=open
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Add comment to inactive issues
        run: |
          const issues = JSON.parse('${{ steps.issues.outputs.data }}');
          const fourDaysAgo = new Date();
          fourDaysAgo.setDate(fourDaysAgo.getDate() - 4);
          
          for (const issue of issues) {
            const lastActivityDate = new Date(issue.updated_at);
            if (lastActivityDate < fourDaysAgo && issue.comments === 0) {
              const body = {
                issue_number: issue.number,
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.repository }}',
                body: "It seems there has been no activity on this issue for the past four days. If you still require assistance, please let us know."
              };

              const octokit = require('@octokit/rest')();
              octokit.authenticate({
                type: 'token',
                token: process.env.GITHUB_TOKEN
              });

              octokit.issues.createComment(body);
            }
          }
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
