name: 'Without'

on:
  workflow_dispatch:

jobs:
  comment_on_inactive_issues:
    runs-on: ubuntu-latest
    
    steps:
      - name: Comment on inactive issues
        uses: actions/github-script@v6
        with:
          script: |
            const creator = context.payload.sender.login;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const currentDateTimeMinusFourDays = new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString();
            
            const issues = await github.paginate(github.rest.issues.listForRepo({
              owner: owner,
              repo: repo,
              state: 'open'
            }));

            for (const issue of issues) {
              const comments = await github.rest.issues.listComments({
                owner: owner,
                repo: repo,
                issue_number: issue.number
              });

              const lastComment = comments.data[comments.data.length - 1];

              if (!lastComment || lastComment.created_at < currentDateTimeMinusFourDays) {
                const comment = `Hello @${owner}! It seems no activity has been recorded on this issue for the past 4 days. Is there anything I can assist you with?`;

                await github.rest.issues.createComment({
                  owner: owner,
                  repo: repo,
                  issue_number: issue.number,
                  body: comment
                });
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
