name: 'without'

on:
  workflow_dispatch:

jobs:
  check_inactive_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add comment to inactive issues
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const octokit = context.github;
            const { owner, repo } = context.repo;

            octokit.issues.listForRepo({
              owner,
              repo,
              state: 'open'
            }).then(({ data: issues }) => {
              const fourDaysAgo = new Date();
              fourDaysAgo.setDate(fourDaysAgo.getDate() - 4);

              issues.forEach(async (issue) => {
                const lastActivityDate = new Date(issue.updated_at);
                if (lastActivityDate < fourDaysAgo && issue.comments === 0) {
                  const commentBody = {
                    issue_number: issue.number,
                    owner,
                    repo,
                    body: "It seems there has been no activity on this issue for the past four days. If you still require assistance, please let us know."
                  };

                  await octokit.issues.createComment(commentBody);
                }
              });
            });
